"""
AI Service for integrating with Google Gemini API
Handles text generation for summaries and grammar correction
"""

import google.generativeai as genai
from typing import Literal
from backend.core.config import settings


class GeminiService:
    """Service class for Google Gemini API integration"""
    
    def __init__(self):
        self.api_key = settings.GEMINI_API_KEY
        # Configure the Gemini API with the API key
        if self.api_key:
            genai.configure(api_key=self.api_key)
            self.model = genai.GenerativeModel('models/gemini-1.5-pro')
        else:
            self.model = None
    
    def _build_prompt(self, content: str, task_type: Literal["summary", "grammar"]) -> str:
        """
        Build appropriate prompt based on task type
        
        Args:
            content: The blog content to process
            task_type: Either "summary" or "grammar"
        
        Returns:
            Formatted prompt string
        """
        if task_type == "summary":
            return f"""Generate a concise professional summary of the following blog post. 
The summary should be 2-3 sentences and capture the main points clearly.

Blog content:
{content}

Professional Summary:"""
        
        elif task_type == "grammar":
            return f"""Fix all grammar mistakes and improve the clarity of the following text. 
Do not change the meaning or core message. Keep the same tone and style.
Only return the corrected text, without any explanations.

Original text:
{content}

Corrected text:"""
        
        else:
            raise ValueError(f"Invalid task type: {task_type}")
    
    async def generate(
        self, 
        content: str, 
        task_type: Literal["summary", "grammar"]
    ) -> str:
        """
        Generate AI text using Google Gemini API
        
        Args:
            content: The text content to process
            task_type: Type of generation ("summary" or "grammar")
        
        Returns:
            Generated text from Gemini
        
        Raises:
            ValueError: If API key is not configured
            Exception: If API request fails
        """
        if not self.api_key or not self.model:
            raise ValueError("GEMINI_API_KEY not configured in environment")
        
        # Build the prompt
        prompt = self._build_prompt(content, task_type)
        
        try:
            # Generate content using Gemini
            # Note: google-generativeai doesn't have native async support
            # We'll use it synchronously but wrap in FastAPI async endpoint
            response = self.model.generate_content(
                prompt,
                generation_config={
                    "temperature": 0.7,
                    "top_k": 40,
                    "top_p": 0.95,
                    "max_output_tokens": 1024,
                }
            )
            
            # Extract generated text
            if response.text:
                return response.text.strip()
            else:
                raise ValueError("No text generated by Gemini API")
                
        except Exception as e:
            raise Exception(f"Gemini API error: {str(e)}")


# Singleton instance
gemini_service = GeminiService()

