/** @type {import('tailwindcss').Config} */
export default {
    content: [
        "./index.html",
        "./src/**/*.{js,ts,jsx,tsx}",
    ],
    theme: {
        extend: {
            colors: {
                primary: {
                    50: '#faf5ff',
                    100: '#f3e8ff',
                    200: '#e9d5ff',
                    300: '#d8b4fe',
                    400: '#c084fc',
                    500: '#a855f7',
                    600: '#9333ea',
                    700: '#7e22ce',
                    800: '#6b21a8',
                    900: '#581c87',
                    950: '#3b0764',
                },
                accent: {
                    purple: '#a855f7',
                    indigo: '#6366f1',
                    blue: '#3b82f6',
                    cyan: '#06b6d4',
                    teal: '#14b8a6',
                    emerald: '#10b981',
                    amber: '#f59e0b',
                    rose: '#f43f5e',
                    pink: '#ec4899',
                    fuchsia: '#d946ef',
                },
                electric: {
                    blue: '#0ea5e9',
                    purple: '#a855f7',
                    pink: '#ec4899',
                    cyan: '#22d3ee',
                },
                neon: {
                    purple: '#c084fc',
                    pink: '#f472b6',
                    blue: '#60a5fa',
                    green: '#4ade80',
                },
                surface: {
                    50: '#fafafa',
                    100: '#f5f5f5',
                    200: '#e5e5e5',
                    300: '#d4d4d4',
                    400: '#a3a3a3',
                    500: '#737373',
                    600: '#525252',
                    700: '#404040',
                    800: '#262626',
                    900: '#171717',
                    950: '#0a0a0a',
                },
            },
            fontFamily: {
                sans: ['Inter', 'system-ui', '-apple-system', 'sans-serif'],
                display: ['Cal Sans', 'Inter', 'system-ui', 'sans-serif'],
                mono: ['JetBrains Mono', 'Fira Code', 'monospace'],
            },
            boxShadow: {
                'soft': '0 2px 15px -3px rgba(0, 0, 0, 0.07), 0 10px 20px -2px rgba(0, 0, 0, 0.04)',
                'glow': '0 0 30px rgba(168, 85, 247, 0.25)',
                'glow-lg': '0 0 50px rgba(168, 85, 247, 0.35)',
                'glow-xl': '0 0 70px rgba(168, 85, 247, 0.4)',
                'premium': '0 20px 50px -12px rgba(0, 0, 0, 0.15)',
                'premium-lg': '0 25px 60px -15px rgba(0, 0, 0, 0.2), 0 0 40px rgba(168, 85, 247, 0.1)',
                'inner-glow': 'inset 0 0 20px rgba(168, 85, 247, 0.1)',
                'neon': '0 0 20px rgba(168, 85, 247, 0.5), 0 0 40px rgba(168, 85, 247, 0.3)',
                'neon-pink': '0 0 20px rgba(236, 72, 153, 0.5), 0 0 40px rgba(236, 72, 153, 0.3)',
                'neon-blue': '0 0 20px rgba(59, 130, 246, 0.5), 0 0 40px rgba(59, 130, 246, 0.3)',
                'multi': '0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06), 0 0 20px rgba(168, 85, 247, 0.15)',
            },
            backgroundImage: {
                'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))',
                'gradient-premium': 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
                'gradient-mesh': 'linear-gradient(135deg, #667eea 0%, #764ba2 50%, #f093fb 100%)',
                'gradient-cosmic': 'linear-gradient(135deg, #667eea 0%, #764ba2 25%, #f093fb 50%, #4facfe 75%, #00f2fe 100%)',
                'gradient-sunset': 'linear-gradient(135deg, #fa709a 0%, #fee140 100%)',
                'gradient-ocean': 'linear-gradient(135deg, #667eea 0%, #0ea5e9 100%)',
                'gradient-fire': 'linear-gradient(135deg, #f093fb 0%, #f5576c 100%)',
            },
            animation: {
                'float': 'float 6s ease-in-out infinite',
                'float-slow': 'float-slow 20s ease-in-out infinite',
                'glow-pulse': 'glow-pulse 3s ease-in-out infinite',
                'slide-up': 'slide-up 0.5s ease-out',
                'slide-down': 'slide-down 0.5s ease-out',
                'shimmer': 'shimmer 2s linear infinite',
                'fade-in': 'fade-in 0.3s ease-out',
                'scale-in': 'scale-in 0.2s ease-out',
                'bounce-soft': 'bounce-soft 2s ease-in-out infinite',
                'tilt': 'tilt 10s ease-in-out infinite',
                'gradient-shift': 'gradient-shift 8s ease infinite',
                'spin-slow': 'spin 8s linear infinite',
            },
            keyframes: {
                float: {
                    '0%, 100%': { transform: 'translateY(0px)' },
                    '50%': { transform: 'translateY(-20px)' },
                },
                'float-slow': {
                    '0%, 100%': { transform: 'translateY(0px)' },
                    '50%': { transform: 'translateY(-15px)' },
                },
                'glow-pulse': {
                    '0%, 100%': { opacity: '1', boxShadow: '0 0 30px rgba(168, 85, 247, 0.25)' },
                    '50%': { opacity: '0.8', boxShadow: '0 0 50px rgba(168, 85, 247, 0.4)' },
                },
                'slide-up': {
                    '0%': { transform: 'translateY(20px)', opacity: '0' },
                    '100%': { transform: 'translateY(0)', opacity: '1' },
                },
                'slide-down': {
                    '0%': { transform: 'translateY(-20px)', opacity: '0' },
                    '100%': { transform: 'translateY(0)', opacity: '1' },
                },
                shimmer: {
                    '0%': { backgroundPosition: '-1000px 0' },
                    '100%': { backgroundPosition: '1000px 0' },
                },
                'fade-in': {
                    '0%': { opacity: '0' },
                    '100%': { opacity: '1' },
                },
                'scale-in': {
                    '0%': { transform: 'scale(0.95)', opacity: '0' },
                    '100%': { transform: 'scale(1)', opacity: '1' },
                },
                'bounce-soft': {
                    '0%, 100%': { transform: 'translateY(0)' },
                    '50%': { transform: 'translateY(-10px)' },
                },
                tilt: {
                    '0%, 100%': { transform: 'rotate(0deg)' },
                    '25%': { transform: 'rotate(1deg)' },
                    '75%': { transform: 'rotate(-1deg)' },
                },
                'gradient-shift': {
                    '0%, 100%': { backgroundPosition: '0% 50%' },
                    '50%': { backgroundPosition: '100% 50%' },
                },
            },
            backdropBlur: {
                xs: '2px',
            },
            borderRadius: {
                '4xl': '2rem',
                '5xl': '2.5rem',
            },
        },
    },
    plugins: [],
}
