export const theme = {
    ltr: 'ltr',
    rtl: 'rtl',
    paragraph: 'editor-paragraph mb-4',
    quote: 'editor-quote border-l-4 border-gray-300 pl-4 italic text-gray-600',
    heading: {
        h1: 'editor-heading-h1 text-4xl font-bold mb-4 mt-6',
        h2: 'editor-heading-h2 text-3xl font-bold mb-3 mt-5',
        h3: 'editor-heading-h3 text-2xl font-bold mb-2 mt-4',
        h4: 'editor-heading-h4 text-xl font-bold mb-2 mt-3',
        h5: 'editor-heading-h5 text-lg font-bold mb-1 mt-2',
        h6: 'editor-heading-h6 text-base font-bold mb-1',
    },
    list: {
        nested: {
            listitem: 'editor-nested-listitem ml-4',
        },
        ol: 'editor-list-ol list-decimal pl-5 mb-4',
        ul: 'editor-list-ul list-disc pl-5 mb-4',
        listitem: 'editor-listitem mb-1',
    },
    image: 'editor-image',
    link: 'editor-link text-blue-500 hover:underline cursor-pointer',
    text: {
        bold: 'editor-text-bold font-bold',
        italic: 'editor-text-italic italic',
        overflowed: 'editor-text-overflowed',
        hashtag: 'editor-text-hashtag text-blue-600 font-medium',
        underline: 'editor-text-underline underline',
        strikethrough: 'editor-text-strikethrough line-through',
        underlineStrikethrough: 'editor-text-underlineStrikethrough underline line-through',
        code: 'editor-text-code bg-gray-100 dark:bg-gray-800 rounded px-1 py-0.5 font-mono text-sm',
    },
    code: 'editor-code bg-gray-100 dark:bg-gray-800 rounded p-4 font-mono text-sm overflow-x-auto mb-4 block',
    codeHighlight: {
        atrule: 'editor-tokenCb',
        attr: 'editor-tokenCb',
        boolean: 'editor-tokenProperty',
        builtin: 'editor-tokenSelector',
        cdata: 'editor-tokenComment',
        char: 'editor-tokenSelector',
        class: 'editor-tokenFunction',
        'class-name': 'editor-tokenFunction',
        comment: 'editor-tokenComment text-gray-400 italic',
        constant: 'editor-tokenProperty',
        deleted: 'editor-tokenProperty',
        doctype: 'editor-tokenComment',
        entity: 'editor-tokenOperator',
        function: 'editor-tokenFunction text-blue-600',
        important: 'editor-tokenVariable',
        inserted: 'editor-tokenSelector',
        keyword: 'editor-tokenAttr text-purple-600 font-bold',
        namespace: 'editor-tokenVariable',
        number: 'editor-tokenProperty text-red-500',
        operator: 'editor-tokenOperator',
        prolog: 'editor-tokenComment',
        property: 'editor-tokenProperty',
        punctuation: 'editor-tokenPunctuation text-gray-500',
        regex: 'editor-tokenVariable',
        selector: 'editor-tokenSelector',
        string: 'editor-tokenSelector text-green-600',
        symbol: 'editor-tokenProperty',
        tag: 'editor-tokenProperty',
        url: 'editor-tokenOperator',
        variable: 'editor-tokenVariable',
    },
    table: 'PlaygroundEditorTheme__table',
    tableCell: 'PlaygroundEditorTheme__tableCell',
    tableCellHeader: 'PlaygroundEditorTheme__tableCellHeader',
};
