export const theme = {
    ltr: 'ltr',
    rtl: 'rtl',
    placeholder: 'editor-placeholder',
    paragraph: 'editor-paragraph',
    quote: 'editor-quote',
    heading: {
        h1: 'editor-heading-h1',
        h2: 'editor-heading-h2',
        h3: 'editor-heading-h3',
    },
    list: {
        nested: {
            listitem: 'editor-nested-listitem',
        },
        ol: 'editor-list-ol',
        ul: 'editor-list-ul',
        listitem: 'editor-listitem',
    },
    image: 'editor-image',
    link: 'editor-link',
    text: {
        bold: 'editor-text-bold',
        italic: 'editor-text-italic',
        overflowed: 'editor-text-overflowed',
        hashtag: 'editor-text-hashtag',
        underline: 'editor-text-underline',
        strikethrough: 'editor-text-strikethrough',
        underlineStrikethrough: 'editor-text-underlineStrikethrough',
        code: 'editor-text-code',
    },
    code: 'editor-code',
    codeHighlight: {
        atrule: 'editor-tokenAtrule',
        attr: 'editor-tokenAttr',
        boolean: 'editor-tokenBoolean',
        builtin: 'editor-tokenBuiltin',
        cdata: 'editor-tokenCdata',
        char: 'editor-tokenChar',
        comment: 'editor-tokenComment',
        constant: 'editor-tokenConstant',
        deleted: 'editor-tokenDeleted',
        doctype: 'editor-tokenDoctype',
        entity: 'editor-tokenEntity',
        function: 'editor-tokenFunction',
        important: 'editor-tokenImportant',
        inserted: 'editor-tokenInserted',
        keyword: 'editor-tokenKeyword',
        namespace: 'editor-tokenNamespace',
        number: 'editor-tokenNumber',
        operator: 'editor-tokenOperator',
        prolog: 'editor-tokenProlog',
        property: 'editor-tokenProperty',
        punctuation: 'editor-tokenPunctuation',
        regex: 'editor-tokenRegex',
        selector: 'editor-tokenSelector',
        string: 'editor-tokenString',
        symbol: 'editor-tokenSymbol',
        tag: 'editor-tokenTag',
        url: 'editor-tokenUrl',
        variable: 'editor-tokenVariable',
    },
    table: 'editor-table',
    tableCell: 'editor-tableCell',
    tableCellHeader: 'editor-tableCellHeader',
};
